export const defaultErrorLabels = {
  "zh-CN": {
    "INVALID_PURPOSE": "用途无效",
    "AUTH_INVALID": "登录状态无效，请重新登录",
    "INVALID_CREDENTIALS": "用户名或密码错误",
    "USER_DISABLED": "账号已被停用",
    "ACCOUNT_PENDING": "账号尚未通过审批",
    "SESSION_REPLACED": "SESSION_REPLACED",
    "NOT_FOUND": "资源不存在",
    "ADMIN_REQUIRED": "需要管理员权限",
    "ALREADY_LOGGED_IN": "该账号已在其他设备登录",
    "UNKNOWN_DEVICE": "未知设备",
    "ACCOUNT_LOCKED": "登录失败次数过多，请稍后再试",
    "RATE_LIMITED": "请求过于频繁，请稍后再试",
    "SEND_CODE_RATE_LIMITED": "验证码发送过于频繁，请稍后再试",
    "USERNAME_INVALID": "用户名无效",
    "USERNAME_RESERVED": "用户名不可用",
    "USERNAME_ADMIN_LIKE": "用户名不能包含管理员相关字符",
    "USERNAME_TAKEN": "该用户名已注册",
    "PASSWORD_TOO_SHORT": "密码过短",
    "PASSWORD_TOO_LONG": "密码过长",
    "PASSWORD_INCORRECT": "当前密码错误",
    "OLD_PASSWORD_INCORRECT": "旧密码错误",
    "EMAIL_TAKEN": "该邮箱已注册",
    "EMAIL_INVALID": "邮箱无效",
    "EMAIL_UNCHANGED": "新邮箱与当前邮箱相同",
    "EMAIL_MISMATCH": "只能向当前账号邮箱发送验证码",
    "EMAIL_DOMAIN_NOT_ALLOWED": "仅允许带有以下后缀的邮箱注册: {allowed}",
    "EMAIL_DOMAIN_NOT_ALLOWED_CHANGE": "仅允许使用以下后缀的邮箱: {allowed}",
    "EMAIL_NOT_REGISTERED": "该邮箱未注册账号",
    "EMAIL_CHANGE_VIA_ENDPOINT": "请通过 POST /me/email 修改邮箱",
    "EMAIL_VERIFICATION_REQUIRED": "修改邮箱需要新邮箱收到的验证码",
    "EMAIL_CODE_REQUIRED": "请输入邮箱验证码",
    "EMAIL_CODE_TOO_FREQUENT": "验证码发送频繁，请稍后再试",
    "EMAIL_CODE_INVALID": "邮箱验证码错误或已失效",
    "EMAIL_CODE_LOCKED": "验证码错误次数过多，请重新获取验证码",
    "EMAIL_UNAVAILABLE": "邮箱验证不可用",
    "EMAIL_UNAVAILABLE_NO_EMAIL": "账号未绑定邮箱",
    "CODE_INVALID": "验证码错误或已失效",
    "CODE_LOCKED": "验证码错误次数过多，请重新获取验证码",
    "CODE_SENT": "验证码已发送",
    "CODE_VALID": "验证码有效",
    "PASSWORD_RESET_OK": "密码重置成功",
    "PASSWORD_CHANGED_OK": "密码修改成功",
    "CAPTCHA_REQUIRED": "需要图形验证码",
    "CAPTCHA_INVALID": "图形验证码错误或已失效",
    "CAPTCHA_DEPENDENCY_MISSING": "图形验证码需要 Pillow：pip install \"account-kit[captcha]\"",
    "VALIDATION_ERROR": "请求参数无效",
    "ROLE_RESERVED": "admin 不是角色，请使用后台权限标记",
    "ROLE_CODE_TOO_LONG": "角色代码过长",
    "ROLE_INVALID": "角色无效",
    "ROLE_EXISTS": "角色已存在",
    "ROLE_NOT_FOUND": "角色不存在",
    "ROLE_DEFAULT_REQUIRED": "请先把另一个角色设为默认",
    "ROLE_DEFAULT_DELETE": "不能删除默认角色",
    "ROLE_IN_USE": "仍有用户使用该角色",
    "ROLE_UNCHANGED": "已经是该角色",
    "ROLE_CHANGE_PENDING": "已有待审核的角色申请",
    "ROLE_CHANGE_NOT_FOUND": "申请不存在",
    "TIER_CODE_INVALID": "等级代码无效",
    "TIER_EXISTS": "等级已存在",
    "TIER_NOT_FOUND": "等级不存在",
    "TIER_DEFAULT_REQUIRED": "请先把另一个等级设为默认",
    "TIER_DEFAULT_DELETE": "不能删除默认等级",
    "TIER_IN_USE": "仍有用户属于该等级",
    "USER_NOT_FOUND": "用户不存在",
    "USER_ID_INVALID": "user_id 无效",
    "STATUS_INVALID": "状态无效",
    "GENDER_INVALID": "性别无效",
    "BIRTH_FORMAT_INVALID": "出生年月格式无效",
    "BIRTH_IN_FUTURE": "出生年月不能晚于当前月份",
    "BIRTH_INVALID": "出生年月无效",
    "AVATAR_DISABLED": "头像功能未启用",
    "AVATAR_NOT_FOUND": "头像不存在",
    "AVATAR_STORAGE_UNCONFIGURED": "头像存储未配置",
    "AVATAR_EMPTY": "请选择头像图片",
    "AVATAR_TOO_LARGE": "头像不能超过 2MB",
    "MFA_REQUIRED": "该账号已开启两步验证，请升级客户端",
    "MFA_CHALLENGE_INVALID": "登录验证已过期，请重新输入密码登录",
    "MFA_CODE_REQUIRED": "请输入验证码",
    "MFA_CODE_REQUIRED_DELETE": "请输入两步验证码",
    "MFA_CODE_INVALID": "验证码错误",
    "MFA_RECOVERY_INVALID": "恢复码错误",
    "MFA_TOO_MANY_ATTEMPTS": "验证码错误次数过多，请重新登录",
    "MFA_ALREADY_VERIFIED": "已完成验证",
    "TWO_FACTOR_SETUP_REQUIRED": "请先开始设置两步验证",
    "TWO_FACTOR_NOT_ENABLED": "两步验证未开启",
    "DEVICE_NOT_FOUND": "设备不存在",
    "PASSWORD_REQUIRED": "管理员开启两步验证需要当前密码",
    "REFRESH_INVALID": "登录已失效，请重新登录",
    "REFRESH_EXPIRED": "登录已过期，请重新登录",
    "REFRESH_REUSED": "检测到登录凭证被重复使用，已强制下线，请重新登录",
    "ADMIN_DELETE_FORBIDDEN": "不能删除管理员账号",
    "ADMIN_SELF_DELETE_FORBIDDEN": "管理员账号不能自助注销",
    "ADMIN_FLAG_IMMUTABLE": "is_admin 只能由宿主写入，接口不能修改",
    "ADMIN_DEACTIVATE_FORBIDDEN": "不能停用管理员账号",
    "ADMIN_DEACTIVATE_FORBIDDEN_APPROVAL": "不能撤销管理员的审批",
    "ADMIN_IP_FORBIDDEN": "当前 IP 不在管理员白名单",
    "ADMIN_2FA_REQUIRED": "管理员必须先启用两步验证",
    "ADMIN_EMAIL_2FA_FORBIDDEN": "管理员不能使用邮箱验证码作为登录第二因素",
    "ADMIN_ALREADY_EXISTS": "已存在管理员账号",
    "ADMIN_ALREADY_EXISTS_MULTI": "数据库中存在多名管理员，请先清理到恰好一名",
    "ADMIN_ALREADY_EXISTS_OTHER": "已存在其他管理员账号",
    "ADMIN_USERNAME_TAKEN": "该用户名已存在且不是管理员，拒绝接管",
    "ADMIN_EMAIL_TAKEN": "该邮箱已被占用",
    "EMAIL_ACTION_register": "注册账户",
    "EMAIL_ACTION_reset_password": "重置密码",
    "EMAIL_ACTION_change_password": "修改密码",
    "EMAIL_ACTION_login_2fa": "登录验证",
    "EMAIL_ACTION_disable_2fa": "关闭两步验证",
    "EMAIL_ACTION_change_email": "修改账号邮箱",
    "EMAIL_ACTION_delete_account": "注销账号",
    "EMAIL_SUBJECT_login_2fa": "【{brand}】登录验证码",
    "EMAIL_SUBJECT_disable_2fa": "【{brand}】关闭两步验证验证码",
    "EMAIL_SUBJECT_generic": "【{brand}】验证码",
    "REQUEST_FAILED": "请求失败",
    "TWO_FACTOR_ALREADY_ENABLED": "两步验证已开启",
    "TWO_FACTOR_SETUP_EXPIRED": "二维码已过期，请重新开始",
    "TWO_FACTOR_CODE_INVALID": "验证码错误，请确认手机时间准确后重试",
},
  en: {
    "INVALID_PURPOSE": "Invalid purpose",
    "AUTH_INVALID": "Could not validate credentials",
    "INVALID_CREDENTIALS": "Incorrect username or password",
    "USER_DISABLED": "This account has been disabled",
    "ACCOUNT_PENDING": "This account is pending approval",
    "SESSION_REPLACED": "SESSION_REPLACED",
    "NOT_FOUND": "Not found",
    "ADMIN_REQUIRED": "Admin required",
    "ALREADY_LOGGED_IN": "This account is already signed in on another device",
    "UNKNOWN_DEVICE": "unknown device",
    "ACCOUNT_LOCKED": "Too many failed sign-in attempts, please try again later",
    "RATE_LIMITED": "Too many requests, please try again later",
    "SEND_CODE_RATE_LIMITED": "Verification codes sent too often, please try again later",
    "USERNAME_INVALID": "Invalid username",
    "USERNAME_RESERVED": "This username is not available",
    "USERNAME_ADMIN_LIKE": "Username must not contain admin-related words",
    "USERNAME_TAKEN": "Username already registered",
    "PASSWORD_TOO_SHORT": "Password is too short",
    "PASSWORD_TOO_LONG": "Password is too long",
    "PASSWORD_INCORRECT": "Current password is incorrect",
    "OLD_PASSWORD_INCORRECT": "Current password is incorrect",
    "EMAIL_TAKEN": "Email already registered",
    "EMAIL_INVALID": "Invalid email",
    "EMAIL_UNCHANGED": "New email is the same as the current email",
    "EMAIL_MISMATCH": "Codes can only be sent to this account's email",
    "EMAIL_DOMAIN_NOT_ALLOWED": "Only email addresses ending with the following domains may register: {allowed}",
    "EMAIL_DOMAIN_NOT_ALLOWED_CHANGE": "Only email addresses ending with the following domains are allowed: {allowed}",
    "EMAIL_NOT_REGISTERED": "No account is registered with this email",
    "EMAIL_CHANGE_VIA_ENDPOINT": "Change email via POST /me/email",
    "EMAIL_VERIFICATION_REQUIRED": "Changing email requires the code sent to the new address",
    "EMAIL_CODE_REQUIRED": "Please enter the email verification code",
    "EMAIL_CODE_TOO_FREQUENT": "Codes sent too often, please try again later",
    "EMAIL_CODE_INVALID": "Email code is wrong or expired",
    "EMAIL_CODE_LOCKED": "Too many wrong codes, please request a new one",
    "EMAIL_UNAVAILABLE": "Email verification is not available",
    "EMAIL_UNAVAILABLE_NO_EMAIL": "This account has no email address",
    "CODE_INVALID": "The code is wrong or expired",
    "CODE_LOCKED": "Too many wrong codes, please request a new one",
    "CODE_SENT": "Verification code sent",
    "CODE_VALID": "Verification code is valid",
    "PASSWORD_RESET_OK": "Password reset successful",
    "PASSWORD_CHANGED_OK": "Password changed",
    "CAPTCHA_REQUIRED": "Captcha required",
    "CAPTCHA_INVALID": "Captcha is wrong or expired",
    "CAPTCHA_DEPENDENCY_MISSING": "Image captcha needs Pillow: pip install \"account-kit[captcha]\"",
    "VALIDATION_ERROR": "Invalid request",
    "ROLE_RESERVED": "admin is not a role; use the backend admin flag",
    "ROLE_CODE_TOO_LONG": "Role code is too long",
    "ROLE_INVALID": "Invalid role",
    "ROLE_EXISTS": "Role already exists",
    "ROLE_NOT_FOUND": "Role not found",
    "ROLE_DEFAULT_REQUIRED": "Set another role as default first",
    "ROLE_DEFAULT_DELETE": "Cannot delete the default role",
    "ROLE_IN_USE": "The role is still assigned to users",
    "ROLE_UNCHANGED": "Already this role",
    "ROLE_CHANGE_PENDING": "A pending role-change request already exists",
    "ROLE_CHANGE_NOT_FOUND": "Request not found",
    "TIER_CODE_INVALID": "Invalid tier code",
    "TIER_EXISTS": "Tier already exists",
    "TIER_NOT_FOUND": "Tier not found",
    "TIER_DEFAULT_REQUIRED": "Set another tier as default first",
    "TIER_DEFAULT_DELETE": "Cannot delete the default tier",
    "TIER_IN_USE": "The tier is still assigned to users",
    "USER_NOT_FOUND": "User not found",
    "USER_ID_INVALID": "Invalid user_id",
    "STATUS_INVALID": "Invalid status",
    "GENDER_INVALID": "Invalid gender",
    "BIRTH_FORMAT_INVALID": "Invalid birth year-month format",
    "BIRTH_IN_FUTURE": "Birth year-month cannot be after the current month",
    "BIRTH_INVALID": "Invalid birth year-month",
    "AVATAR_DISABLED": "Avatars are not enabled",
    "AVATAR_NOT_FOUND": "Avatar not found",
    "AVATAR_STORAGE_UNCONFIGURED": "Avatar storage is not configured",
    "AVATAR_EMPTY": "Please choose an avatar image",
    "AVATAR_TOO_LARGE": "Avatar must not exceed 2MB",
    "MFA_REQUIRED": "This account has two-factor authentication; please upgrade your client",
    "MFA_CHALLENGE_INVALID": "Sign-in verification expired, please enter your password again",
    "MFA_CODE_REQUIRED": "Please enter the code",
    "MFA_CODE_REQUIRED_DELETE": "Please enter the two-factor code",
    "MFA_CODE_INVALID": "Incorrect code",
    "MFA_RECOVERY_INVALID": "Incorrect recovery code",
    "MFA_TOO_MANY_ATTEMPTS": "Too many wrong codes, please sign in again",
    "MFA_ALREADY_VERIFIED": "Already verified",
    "TWO_FACTOR_SETUP_REQUIRED": "Start two-factor setup first",
    "TWO_FACTOR_NOT_ENABLED": "Two-factor authentication is not on",
    "DEVICE_NOT_FOUND": "Device not found",
    "PASSWORD_REQUIRED": "Admins must enter the current password to turn on two-factor authentication",
    "REFRESH_INVALID": "Session expired, please sign in again",
    "REFRESH_EXPIRED": "Session expired, please sign in again",
    "REFRESH_REUSED": "A refresh token was reused; you have been signed out. Please sign in again",
    "ADMIN_DELETE_FORBIDDEN": "Cannot delete an admin account",
    "ADMIN_SELF_DELETE_FORBIDDEN": "Admin accounts cannot delete themselves",
    "ADMIN_FLAG_IMMUTABLE": "is_admin can only be written by the host, not this API",
    "ADMIN_DEACTIVATE_FORBIDDEN": "Cannot deactivate an admin account",
    "ADMIN_DEACTIVATE_FORBIDDEN_APPROVAL": "Cannot revoke an admin's approval",
    "ADMIN_IP_FORBIDDEN": "This IP is not on the admin allowlist",
    "ADMIN_2FA_REQUIRED": "Admins must enable two-factor authentication first",
    "ADMIN_EMAIL_2FA_FORBIDDEN": "Admins cannot use an email code as the login second factor",
    "ADMIN_ALREADY_EXISTS": "An admin account already exists",
    "ADMIN_ALREADY_EXISTS_MULTI": "Multiple admin accounts exist; keep exactly one",
    "ADMIN_ALREADY_EXISTS_OTHER": "A different admin account already exists",
    "ADMIN_USERNAME_TAKEN": "This username exists and is not admin; takeover refused",
    "ADMIN_EMAIL_TAKEN": "This email is already in use",
    "EMAIL_ACTION_register": "register",
    "EMAIL_ACTION_reset_password": "reset your password",
    "EMAIL_ACTION_change_password": "change your password",
    "EMAIL_ACTION_login_2fa": "sign in",
    "EMAIL_ACTION_disable_2fa": "turn off two-factor authentication",
    "EMAIL_ACTION_change_email": "change your account email",
    "EMAIL_ACTION_delete_account": "delete your account",
    "EMAIL_SUBJECT_login_2fa": "[{brand}] Your sign-in verification code",
    "EMAIL_SUBJECT_disable_2fa": "[{brand}] Code to turn off two-step verification",
    "EMAIL_SUBJECT_generic": "[{brand}] Verification code",
    "REQUEST_FAILED": "Request failed",
    "TWO_FACTOR_ALREADY_ENABLED": "Two-step verification is already on",
    "TWO_FACTOR_SETUP_EXPIRED": "QR code expired, please start again",
    "TWO_FACTOR_CODE_INVALID": "Incorrect code. Check that your phone's time is correct",
},
} as const

export type ErrorCode = keyof typeof defaultErrorLabels["zh-CN"]
